package lt.vu.mybatis.dao;

import java.util.List;
import lt.vu.mybatis.model.Sponsor;
import org.mybatis.cdi.Mapper;

@Mapper
public interface SponsorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SPONSOR
     *
     * @mbg.generated Mon Apr 01 16:41:39 EEST 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SPONSOR
     *
     * @mbg.generated Mon Apr 01 16:41:39 EEST 2024
     */
    int insert(Sponsor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SPONSOR
     *
     * @mbg.generated Mon Apr 01 16:41:39 EEST 2024
     */
    Sponsor selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SPONSOR
     *
     * @mbg.generated Mon Apr 01 16:41:39 EEST 2024
     */
    List<Sponsor> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SPONSOR
     *
     * @mbg.generated Mon Apr 01 16:41:39 EEST 2024
     */
    int updateByPrimaryKey(Sponsor record);
}