package lt.vu.mybatis.model;

public class Sponsor {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SPONSOR.ID
     *
     * @mbg.generated Mon Apr 01 16:41:39 EEST 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SPONSOR.NAME
     *
     * @mbg.generated Mon Apr 01 16:41:39 EEST 2024
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SPONSOR.ID
     *
     * @return the value of PUBLIC.SPONSOR.ID
     *
     * @mbg.generated Mon Apr 01 16:41:39 EEST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SPONSOR.ID
     *
     * @param id the value for PUBLIC.SPONSOR.ID
     *
     * @mbg.generated Mon Apr 01 16:41:39 EEST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SPONSOR.NAME
     *
     * @return the value of PUBLIC.SPONSOR.NAME
     *
     * @mbg.generated Mon Apr 01 16:41:39 EEST 2024
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SPONSOR.NAME
     *
     * @param name the value for PUBLIC.SPONSOR.NAME
     *
     * @mbg.generated Mon Apr 01 16:41:39 EEST 2024
     */
    public void setName(String name) {
        this.name = name;
    }
}